# Fichier: .chainlit/config.toml

[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://github.com/Chainlit/chainlit/issues/441)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads when a user starts a new chat session.
auto_tag_thread = true

# Authorize users to upload files with messages
multi_modal = true

# Allows user to use speech to text
[features.speech_to_text]
    enabled = false
    # See all languages here https://github.com/JamesBrill/react-speech-kit#language-support
    # language = "fr-FR"
[features.audio]
    # Threshold for audio recording
    min_decibels = -45
    # Delay for the user to start speaking in MS
    initial_silence_timeout = 3000
    # Delay for the user to continue speaking in MS. If the user stops speaking for this duration, the recording will stop.
    silence_timeout = 1500
    # Above this duration (MS), the recording will forcefully stop.
    max_duration = 15000
    # Duration of the audio chunks in MS
    chunk_duration = 1000
    # Sample rate of the audio
    sample_rate = 44100


[UI]
# Name of the app and chatbot.
name = "Sunu Stat - ANSD"

# Show the readme while the conversation is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
description = "Assistant Intelligent pour les Statistiques du Sénégal - ANSD (Agence Nationale de la Statistique et de la Démographie)"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = "https://github.com/sallfatima/sun-stats.git"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
#custom_css = "/public/style.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
custom_js = "/public/script.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"

# Specify a custom build directory for the UI. This is used to serve the UI from a different location.
# custom_build = "./public/build"

# Configuration pour la langue française
default_locale = "fr-FR"

# Masquer le watermark "Built with Chainlit"
show_watermark = false


custom_css = "/public/hide_watermark.css"

# Override default MUI light theme. (Check theme.ts)
[UI.theme]
    default = "dark"
    #layout = "wide"
    # Override the default font family.
    font_family = "Roboto, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif"

[UI.theme.light]
    #background = "#FAFAFA"
    #paper = "#FFFFFF"

    [UI.theme.light.primary]
        #main = "#F80061"
        #dark = "#980039"
        #light = "#FFE7EB"

[UI.theme.dark]
    background = "#162CF8"
    paper = "rgba(255, 255, 255, 0.1)"

    [UI.theme.dark.primary]
        main = "#F63D15"
        dark = "#E2A31B"
        light = "#1a2ef5"

[meta]
generated_by = "1.0.200"